# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1496abc3a081a9b0a8bdced76fac9a317e100778ad38c3aff7ac5835775359d436a250cecfec96aa9d8f2b99755190bba1a25dde13c83df007b362046e445d06

test:
  secret_key_base: 5560b5358bb48b03cedf88c80e2f0ff2153d4282f289b191fe2b083bea4920e9f3bf601532df4fd14deaecd580e4158f78f54b22aa9a0a54360f594ce8575dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
